name: MagicTool

on:
  push:
    branches:
      - '*' # Exécute le workflow à chaque commit sur toutes les branches
  schedule:
    - cron: '0 0 */2 * *' # Toutes les 6 heures, vous pouvez ajuster la fréquence selon vos besoins

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: rattingimanj/Makfn-Fortnite-Internal-SelfLeak
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0  # Cloner toutes les branches

      - name: Set up Git
        run: |
          git config --global user.email "KingOfHeel@youtube.com"
          git config --global user.name "KingOfHeel"

      - name: Add Destination Remote
        run: git remote add destination https://github.com/saitokouna/rattingimanj_Makfn-Fortnite-Internal-SelfLeak.git

      - name: Push to Destination Repository
        run: git push destination --mirror
